name = "orbis"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[env.production]
account_id = "9352cf03e38b96ca848d2b3a55819885"

# Pages configuration
[pages]
# Build command is handled by CI/CD
# dist directory contains the built files 